# Generated by Django 6.0.2 on 2026-02-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the person', max_length=150)),
                ('role', models.CharField(default='Course Graduate', help_text='e.g., "Course Graduate", "Data Analyst at XYZ"', max_length=100)),
                ('text', models.TextField(help_text='Testimonial quote')),
                ('rating', models.PositiveSmallIntegerField(default=5, help_text='Rating from 1 to 5')),
                ('is_active', models.BooleanField(default=True, help_text='Only active testimonials are shown on the site')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
