# Generated by Django 6.0.2 on 2026-02-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, help_text='Profile image (optional)', null=True, upload_to='testimonials/'),
        ),
    ]
