# Generated by Django 6.0.2 on 2026-02-10 18:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='auto_calculate_badges',
            field=models.BooleanField(default=True, help_text='Auto-calculate badges based on rules'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_hot',
            field=models.BooleanField(default=False, help_text='Manually mark as HOT'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_new',
            field=models.BooleanField(default=False, help_text='Manually mark as NEW'),
        ),
        migrations.AddField(
            model_name='program',
            name='is_professional',
            field=models.BooleanField(default=False, help_text='Manually mark as PROFESSIONAL'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('dropped', 'Dropped'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Overall completion percentage (0-100)', max_digits=5)),
                ('payment_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='not_required', max_length=20)),
                ('payment_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_reference', models.CharField(blank=True, help_text='Payment gateway reference/transaction ID', max_length=255)),
                ('program', models.ForeignKey(help_text='Program the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='programs.program')),
                ('student', models.ForeignKey(help_text='Student enrolled in the program', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'enrollment',
                'verbose_name_plural': 'enrollments',
                'ordering': ['-enrolled_at'],
                'unique_together': {('student', 'program')},
            },
        ),
        migrations.CreateModel(
            name='ProgramModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Module title', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Module description/overview')),
                ('order', models.IntegerField(default=0, help_text='Display order within program')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(help_text='Program this module belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='programs.program')),
            ],
            options={
                'verbose_name': 'program module',
                'verbose_name_plural': 'program modules',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Lesson title', max_length=255)),
                ('content', models.TextField(help_text='Rich text lesson content (HTML)')),
                ('duration_minutes', models.IntegerField(default=0, help_text='Estimated duration in minutes')),
                ('order', models.IntegerField(default=0, help_text='Display order within module')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, Vimeo, or other video URL', null=True)),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs/files')),
                ('is_preview', models.BooleanField(default=False, help_text='Allow non-enrolled students to preview this lesson')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(help_text='Module this lesson belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='programs.programmodule')),
            ],
            options={
                'verbose_name': 'lesson',
                'verbose_name_plural': 'lessons',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, help_text='Whether student has completed this lesson')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the lesson was completed', null=True)),
                ('time_spent_minutes', models.IntegerField(default=0, help_text='Total time spent on this lesson')),
                ('last_accessed', models.DateTimeField(auto_now=True, help_text='Last time student accessed this lesson')),
                ('enrollment', models.ForeignKey(help_text='Enrollment this progress belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to='programs.enrollment')),
                ('lesson', models.ForeignKey(help_text='Lesson being tracked', on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='programs.lesson')),
            ],
            options={
                'verbose_name': 'lesson progress',
                'verbose_name_plural': 'lesson progress records',
                'ordering': ['lesson__module__order', 'lesson__order'],
                'unique_together': {('enrollment', 'lesson')},
            },
        ),
        migrations.CreateModel(
            name='ProgramInstructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary instructor for this program')),
                ('assigned_by', models.ForeignKey(help_text='Admin who made the assignment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_assignments', to=settings.AUTH_USER_MODEL)),
                ('instructor', models.ForeignKey(help_text='Instructor teaching this program', limit_choices_to={'role': 'instructor'}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_programs', to=settings.AUTH_USER_MODEL)),
                ('program', models.ForeignKey(help_text='Program being taught', on_delete=django.db.models.deletion.CASCADE, related_name='assigned_instructors', to='programs.program')),
            ],
            options={
                'verbose_name': 'program instructor',
                'verbose_name_plural': 'program instructors',
                'ordering': ['-is_primary', 'assigned_at'],
                'unique_together': {('program', 'instructor')},
            },
        ),
    ]
